CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: 006Tdc8jxw84FwFFZIIusv2l
CONTACT_EMAIL: contact@local.overhang.io
DISCOVERY_MYSQL_PASSWORD: 0FuN1sei
DISCOVERY_OAUTH2_SECRET: 5jRGYGoI
DISCOVERY_OAUTH2_SECRET_SSO: 1mC7ICUw
DISCOVERY_SECRET_KEY: 3DjuTfke29WlW5iYxJcH
ENABLE_HTTPS: false
ID: TEOJWlWkdMZ2iJEwCbGj0GnB
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAxCPURKU+XxJgJ+7IBPr5o3rpxG4UvS/NAl1LpLkdXlDz0l0C

  elR+yXSv3PJDeFkwEH/1YKR85CgkxZWAIwnykOz0XcYg0hXbEPn97qWVwcuOiDvO

  uZriKQYN8Mc9QmZKV4/dag4i4c1YATyhXqxaY/HpjDlR5Ur+4lJsKsWKXofFCfeL

  irQuOyFYQy3ovXrflY510HBprkVmFOGcQs0AijD6U3WYOEq+dCbIwm6z+8j4TxiD

  dFE4S/LHdq+LdQAlYfQIyvsosgx0Zu70b5c8kyOcZUvGUnnnnf9noH9r7KizV4DO

  wfpwRVlwY3PPeXXRKtTBZiA0ZX7AhB/rXuEobQIDAQABAoIBAAxj5wjfF22SD5j2

  MJR/9j0pipLqEU1SM7Uuh5TETOKkYoKrdXic1dWMFX/zneeAWtTwAGQ2f9052/jP

  VOThv/z/uwAhf/lFgC02XaAxvaAcZ8ibXpfC/P5yb3cCXxBOveuCHw6QDgwNmL2b

  QuZkJOGjaol9JXtCnY9WfZbGG9OUy8ASsTJi5njMYcbW0LSUbphyx1CUtyfkuDst

  CdBJshjBTY/1z+8N39hU6y3c0bRtA5QeHglm3uk9Z//Z6fxkKcW1DmR92gGRhiaV

  8c5VX9YO4zkQogRuy5NgXLVK05CntvQQh9Sw6gGgit5BYzaFI6s96Ka9eljp7INF

  LMXYmVECgYEA2tV5pimS+GabY+W//ERPewMLeBPda+Qz67kcj9lQ86UZRsRDWPb6

  rqkqcUbLPI8cHFUVPU4yUraZcnn2K+bERrdsTyrAZNVQndzg/7BWckH5UvV83wXs

  x38ahwVFGqsJ0pYV+jmvRkVor6jyEE4L7qxCPaihuJXBcWbLtrLSaYcCgYEA5XOp

  Gj5+5nOivATYD+F6WKU5i4D2cITR5zIjOZgD8Qp6fswU0eA+Et84efBicSn4yxZa

  NJ4Go0njxHYNG+NvLu/b0MfKEc+nU3DR09VROmYFWoGgNmIFFhe5lk0YoDDYiHe9

  slLSSzvjHkxsYmvyxwQKPDfMFQQo0KYBV9r3y2sCgYBbOVKU6g/SbTOp2UTHLNLV

  PNezHtTW/TKHuYsmjDkq2FBJJ9fLZmnqFasTvadLf30AcpeADvD7ehNNnXn5oyF/

  OUd1WSUK48HPjRxeemwPBWGiK6P6dMXYBCxSzOeZzmMx3k8bGKDwck7Jq2v9UAu5

  WyXh/kIsaIFTfL6/UpxUUQKBgQC/Uj+wiGfb1JPe3tMh+sq/W5WuAux6SeWUN7Qz

  c9Pliu01CQpbLfXUWpiG5K/Q2ESBYrP4p8O1KAlpaV3o4S12H75USiLt0w4cfzgW

  wAoo/aR9IRTsA7NmBoZTExnziIck02Mza+e5n8fzHZpKPuSCmZXHPGdJJty5jZIV

  JZn03QKBgQClFkyhcIxmNXKBD14+oUpUFV5lawiY3gAVnhO4MhlqMXmmtxD6EESB

  DJoUQKXAexK7vVtbAX6v5UByuLSTguduFrkFOYsgirnZ29fb9rmqLsf5rm5Av1ey

  sGS3C4mlgqlku0q8yOP1vHdvtKTno6qzU+QMBqdwaxmQ9JAxbCmIqQ==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: QiS85k6e
NOTES_MYSQL_PASSWORD: irkCb2zd
NOTES_OAUTH2_SECRET: NmYxtr1MIweEQhGngg8TBUra
NOTES_REPOSITORY: https://jayram.nai:3yqFkbSofzNJnPZ6RUsd@git.drcsystems.com/mooc/nsdc-note.git
NOTES_REPOSITORY_VERSION: 21032023-1/notes.maple.master
NOTES_SECRET_KEY: hWXMS4W0re9wWKDcxzXHh2kq
OPENEDX_LMS_UWSGI_WORKERS: 3
OPENEDX_MYSQL_PASSWORD: V5lRpCq1
OPENEDX_SECRET_KEY: bNu0FXp77dOFFjn6eygBVKAt
PLATFORM_NAME: My Open edX
PLUGINS:
- discovery
- forum
- mfe
- s3
- timezone
