version: "3.7"
services:

    mysql-job:
      image: docker.io/mysql:5.7.35
      depends_on: ["mysql"]

    lms-job:
      image: docker.io/overhangio/openedx:14.2.4
      environment:
        SERVICE_VARIANT: lms
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb"]

    cms-job:
      image: docker.io/overhangio/openedx:14.2.4
      environment:
        SERVICE_VARIANT: cms
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
      volumes:
        - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
        - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
        - ../apps/openedx/config:/openedx/config:ro
      depends_on: ["mysql", "mongodb", "elasticsearch", "redis"]

    discovery-job:
      image: docker.io/overhangio/openedx-discovery:14.0.2
      environment:
        DEFAULT_PARTNER_CODE: openedx
      volumes:
        - ../plugins/discovery/apps/settings/tutor:/openedx/discovery/course_discovery/settings/tutor:ro
      depends_on: ["lms", "mysql"]
    forum-job:
      image: docker.io/overhangio/openedx-forum:14.0.0
      environment:
        SEARCH_SERVER: "http://elasticsearch:9200"
        MONGODB_AUTH: ""
        MONGODB_HOST: "mongodb"
        MONGODB_PORT: "27017"
        MONGODB_DATABASE: "cs_comments_service"
      depends_on: ["elasticsearch", "mongodb"]