version: "3.7"

x-openedx-service:
  &openedx-service
  image: openedx-dev:14.2.4
  build:
    context: ../build/openedx/
    target: development
    args:
      # Note that we never build the openedx-dev image with root user ID, as it would simply fail.
      APP_USER_ID: "1000"
  stdin_open: true
  tty: true
  volumes:
    # Settings & config
    - ../apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
    - ../apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
    - ../apps/openedx/config:/openedx/config:ro
    # theme files
    - ../build/openedx/themes:/openedx/themes
    # editable requirements
    - ../build/openedx/requirements:/openedx/requirements

services:
  lms-permissions:
    command: ["1000", "/openedx/data", "/openedx/media"]

  cms-permissions:
    command: ["1000", "/openedx/data", "/openedx/media"]

  lms:
    <<: *openedx-service
    command: ./manage.py lms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: lms.envs.tutor.development
    ports:
        - "8000:8000"
    networks:
      default:
        aliases:
          - "local.overhang.io"

  cms:
    <<: *openedx-service
    command: ./manage.py cms runserver 0.0.0.0:8000
    environment:
        DJANGO_SETTINGS_MODULE: cms.envs.tutor.development
    ports:
        - "8001:8000"

  lms-worker:
    <<: *openedx-service

  cms-worker:
    <<: *openedx-service

  # Additional service for watching theme changes
  watchthemes:
    <<: *openedx-service
    command: openedx-assets watch-themes --env dev
    restart: unless-stopped

  discovery:
    environment:
      DJANGO_SETTINGS_MODULE: course_discovery.settings.tutor.development
    command: ./manage.py runserver 0.0.0.0:8381
    stdin_open: true
    tty: true
    ports:
      - "8381:8381"
    networks:
      default:
        aliases:
          - "discovery.local.overhang.io"
  forum:
    stdin_open: true
    tty: true
  # MFE apps

  account:
      image: account
      build:
          context: ../plugins/mfe/build/mfe/
          target: account-dev
      ports:
          - "1997:1997"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
      env_file:
          - ../plugins/mfe/build/mfe/env/production
          - ../plugins/mfe/build/mfe/env/development
      environment:
          - "PORT=1997"
          - "COACHING_ENABLED="
          
          - "ENABLE_DEMOGRAPHICS_COLLECTION="
          

  gradebook:
      image: gradebook
      build:
          context: ../plugins/mfe/build/mfe/
          target: gradebook-dev
      ports:
          - "1994:1994"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
      env_file:
          - ../plugins/mfe/build/mfe/env/production
          - ../plugins/mfe/build/mfe/env/development
      environment:
          - "PORT=1994"

  learning:
      image: learning
      build:
          context: ../plugins/mfe/build/mfe/
          target: learning-dev
      ports:
          - "2000:2000"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
      env_file:
          - ../plugins/mfe/build/mfe/env/production
          - ../plugins/mfe/build/mfe/env/development
      environment:
          - "PORT=2000"

  profile:
      image: profile
      build:
          context: ../plugins/mfe/build/mfe/
          target: profile-dev
      ports:
          - "1995:1995"
      stdin_open: true
      tty: true
      volumes:
          - ../plugins/mfe/apps/mfe/webpack.dev-tutor.config.js:/openedx/app/webpack.dev-tutor.config.js:ro
      env_file:
          - ../plugins/mfe/build/mfe/env/production
          - ../plugins/mfe/build/mfe/env/development
      environment:
          - "PORT=1995"
          - "ENABLE_LEARNER_RECORD_MFE=true"
          
